# Generated by Django 4.0.4 on 2022-06-27 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=200)),
                ('affichage', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PostPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('nb_affichage', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=200)),
                ('Niveau', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('attente', 'Attente'), ('publier', 'publier')], default='attente', max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('avant', models.CharField(max_length=200)),
                ('publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category_post', to='blog.category')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.postplan')),
            ],
        ),
    ]
