# Generated by Django 4.0.4 on 2022-05-24 21:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postplan',
            name='publication',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 24, 21, 23, 26, 671148, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postplan',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
