# Generated by Django 4.0.4 on 2022-05-26 20:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_postplan_publication_alter_postplan_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postplan',
            name='publication',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 20, 8, 18, 270973, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('body', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.postplan')),
            ],
        ),
    ]
