# Generated by Django 4.0.4 on 2022-05-26 20:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_postplan_publication_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='postplan',
            name='publication',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 20, 8, 54, 905975, tzinfo=utc)),
        ),
    ]
