# Generated by Django 4.0.4 on 2022-05-26 20:50

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_alter_postplan_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postplan',
            name='type_village',
        ),
        migrations.RemoveField(
            model_name='postplan',
            name='usage',
        ),
        migrations.AddField(
            model_name='postplan',
            name='Description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postplan',
            name='level',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='postplan',
            name='publication',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 20, 50, 14, 131976, tzinfo=utc)),
        ),
    ]
