# Generated by Django 4.0.4 on 2022-05-26 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_adresse_plan_postplan_adresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postplan',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Category_post', to='blog.category'),
            preserve_default=False,
        ),
    ]
