# Generated by Django 4.0.4 on 2022-05-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_postplan_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='postplan',
            name='tag',
            field=models.CharField(default=12, max_length=200),
            preserve_default=False,
        ),
    ]
