# Generated by Django 4.0.4 on 2022-05-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_postplan_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='affichage',
            field=models.CharField(default=23, max_length=200),
            preserve_default=False,
        ),
    ]
