# Generated by Django 4.0.4 on 2022-05-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_category_affichage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='message',
        ),
    ]
